---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {APP_NAME}-constants-prod-batch
  namespace: {KUBE_KOB_NAMESPACE}
data:
  API_NAME: {APP_NAME}
  API_VERSION: {APP_VERSION}
  ENVIRONMENT: {APP_ENV}
  DATACENTER: {ENV_DATACENTER}
  KOB_NAMESPACE: {KUBE_KOB_NAMESPACE}
  TYPE: 'BATCH'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {APP_NAME}-constants-prod-fast
  namespace: {KUBE_KOB_NAMESPACE}
data:
  API_NAME: {APP_NAME}
  API_VERSION: {APP_VERSION}
  ENVIRONMENT: {APP_ENV}
  DATACENTER: {ENV_DATACENTER}
  KOB_NAMESPACE: {KUBE_KOB_NAMESPACE}
  TYPE: 'FAST'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APP_NAME}-deployment-green-prod-batch
  namespace: {KUBE_KOB_NAMESPACE}
  labels:
    app: {APP_NAME}
    version: 'green'
    environment: 'prod'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {APP_NAME}
      version: 'green'
      environment: 'prod'
      variant: 'batch'
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: {APP_NAME}
        version: 'green'
        environment: 'prod'
        variant: 'batch'
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: {APP_NAME}
          image: harbor.dell.com/soas-ds/ip-content-management:{BUILD_VERSION}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8Gi"
              cpu: "3"
            limits:
              memory: "8Gi"
              cpu: "3"
          env:
          - name: MAX_WORKERS
            value: "1"
          - name: AUTOWRAPT_BOOTSTRAP
            value: autodynatrace
          - name: AUTODYNATRACE_APPLICATION_ID
            value: ip_content_management
          - name: AUTODYNATRACE_FORKABLE
            value: "true"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {APP_NAME}-constants-prod-batch
      securityContext:
        sysctls:
            - name: net.ipv4.ip_unprivileged_port_start
              value: "80"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APP_NAME}-deployment-green-prod-fast
  namespace: {KUBE_KOB_NAMESPACE}
  labels:
    app: {APP_NAME}
    version: 'green'
    environment: 'prod'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {APP_NAME}
      version: 'green'
      environment: 'prod'
      variant: 'fast'
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: {APP_NAME}
        version: 'green'
        environment: 'prod'
        variant: 'fast'
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: {APP_NAME}
          image: harbor.dell.com/soas-ds/ip-content-management:{BUILD_VERSION}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8Gi"
              cpu: "4"
            limits:
              memory: "8Gi"
              cpu: "4"
          env:
          - name: MAX_WORKERS
            value: "1"
          - name: AUTOWRAPT_BOOTSTRAP
            value: autodynatrace
          - name: AUTODYNATRACE_APPLICATION_ID
            value: ip_content_management
          - name: AUTODYNATRACE_FORKABLE
            value: "true"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {APP_NAME}-constants-prod-fast
      securityContext:
        sysctls:
            - name: net.ipv4.ip_unprivileged_port_start
              value: "80"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {APP_NAME}-autoscaler-green-prod-batch
  namespace: {KUBE_KOB_NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {APP_NAME}-deployment-green-prod-batch
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {APP_NAME}-autoscaler-green-prod-fast
  namespace: {KUBE_KOB_NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {APP_NAME}-deployment-green-prod-fast
  minReplicas: 4
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90