alter table ciq_fssit.tdocument 
ADD COLUMN projectid varchar(100),
ADD COLUMN uploadedby varchar(100),
ADD COLUMN author varchar(100);

ALTER TABLE ciq_fssit.tdocument DROP CONSTRAINT tdocument_pkey;
ALTER TABLE ciq_fssit.tdocument ADD CONSTRAINT tdocument_pk PRIMARY KEY (requestid, daoriginal_fileid, dafileid);

            	          
drop table if exists ciq_fssit.config;
CREATE TABLE config (
	id serial4 NOT NULL,
	name varchar(255) NOT NULL,
	val varchar(255) not NULL,
	comment varchar(255) null,
	isactive boolean default true,
	inserted_on timestamp DEFAULT (now() AT TIME ZONE 'UTC'::text) NULL,
	updated_on timestamp NULL,
	CONSTRAINT config_pkey PRIMARY KEY (id)
);

insert into ciq_fssit.config (name,val,comment,isactive)
values
('KAFKA_BOOTSTRAP_SERVERS_OUTPUT','ckfnlpc1ncsgb01.amer.dell.com:9093,ckfnlpc1ncsgb02.amer.dell.com:9093,ckfnlpc1ncsgb03.amer.dell.com:9093,ckfnlpc1ncsgb04.amer.dell.com:9093','Kafka config',true),
('KAFKA_BOOTSTRAP_SERVERS_INPUT','ckfnlpc1svcb01.amer.dell.com:9093,ckfnlpc1svcb02.amer.dell.com:9093,ckfnlpc1svcb03.amer.dell.com:9093,ckfnlpc1svcb04.amer.dell.com:9093','Kafka config',true),
('KAFKA_GROUP_ID','secure-test-group','Kafka config',true),
('INPUT_TOPICS','SDS.EDP.CONSLTIQ.EVENTS.GE4','Kafka config',true),
('OUTPUT_TOPIC','CSG.TAA.SERVICESAI.DEV.CONSULT.DEV','Kafka config',true),
('SECURITY_PROTOCOL','SASL_SSL','Kafka config',true),
('SASL_MECHANISM','PLAIN','Kafka config',true),
('AUTO_OFFSET_RESET','earliest','Kafka config',true),
('ENABLE_AUTO_COMMIT','true','Kafka config',true),
('SERVICE_NAME','summerization_service','',false),
('LOG_LEVEL','INFO','Kafka config',true),
('HEALTH_CHECK_PORT','8080','Kafka config',true),
('ENVIRONMENT','testing','deployment',true),
('USE_SSO','false','Gen Ai',true),
('ENABLE_TOKEN_REFRESH_AT_SERVER_SIDE','false','Gen Ai',true),
('GEN_AI_API_LINK','https://aia.gateway.dell.com/genai/dev/v1','Gen Ai',true),
('INDIR','./ip_content_management/input','global',true),
('OUTDIR','./ip_content_management/output','global',true),
('DELL_ATTACHMENTS_SERVICE_TYPE','PDE','dell attachments',true),
('DELL_ATTACHMENTS_URL','https://apigtwtst.us.dell.com/filesUpload','dell attachments',true),
('DELL_ATTACHMENTS_CHUNK_SIZE','2000000','dell attachments',true),
('DELL_ATTACHMENTS_AUTH_URL','https://apigtwtst.us.dell.com/auth/oauth/v2/token','dell attachments',true),
('DELL_ATTACHMENTS_USER_ID','lekhnath.pandey@dellteam.com','dell attachments',true),
('DELL_ATTACHMENTS_INITIATE_ENDPOINT','/v1/file/upload/initiate','dell attachments',true),
('DELL_ATTACHMENTS_STREAM_ENDPOINT','/v1/file/upload/stream','dell attachments',true),
('DELL_ATTACHMENTS_COMPLETE_ENDPOINT','/v1/file/upload/initiate/complete','dell attachments',true),
('DELL_ATTACHMENTS_STATUS_ENDPOINT','/v1/files/status','dell attachments',true),
('DELL_ATTACHMENTS_DOWNLOAD_ENDPOINT','/v1/file/download/{fileid}/fileID','dell attachments',true),
('DELL_ATTACHMENTS_LISTFILES_ENDPOINT','/v1/file/download/metadata','dell attachments',true),
('CORR_ID_CLASSIFICATION','f91fa045-8e36-4581-9ae3-b7a9cc21b251','Gen Ai',true),
('CORR_ID_REDACTION','75780abc-dda3-4dbe-a535-b639a67425fc','Gen Ai',true),
('CORR_ID_SUMMARIZATION','47ec5b06-7930-4b8b-bafd-980cea5acd6a','Gen Ai',true),
('CORR_ID_EMBEDDINGS','662f0f9b-1e88-4f03-bf9e-f259ecc67965','Gen Ai',true),
('CORR_ID_DELIVERY_KIT_SUMMARIZATION',' 66e4182a-66cf-48cb-84dd-ba7e96ae002b','Gen Ai',true),
('DEBUG','False','global',true),
('IMAGE_ANALYZE_SWITCH','True','gtl flow',true),
('CHUNK_SIZE_REDACTION','50000','gtl flow',true),
('OVER_LAP_SIZE_REDACTION','200','gtl flow',true),
('PREFIX','','gtl flow',true),
('LLM_PREFIX','','gtl flow',true),
('REGEX_PREFIX','RegEx','gtl flow',true),
('REDACTION_THRESHOLD_XLSX','0.5','gtl flow',true),
('REDACTION_THRESHOLD_DOCX','0.5','gtl flow',true),
('REDACTION_THRESHOLD_PPTX','0.5','gtl flow',true),
('REDACTION_THRESHOLD_OTHERS','0.5','gtl flow',true),
('CHUNK_SIZE_CLASSIFICATION','50000','gtl flow',true),
('OVER_LAP_SIZE_CLASSIFICATION','200','gtl flow',true),
('CHUNK_SIZE_RECOMMENDATION','25000','consultant flow',true),
('OVER_LAP_SIZE_RECOMMENDATION','200','consultant flow',true),
('THRESHOLD_SOW_OFFER_SCORE','0.6','consultant flow',true),
('THRESHOLD_DOC_OFFER_SCORE','0.6','gtl flow',true),
('THRESHOLD_DOC_TYPE_SCORE','0.6','gtl flow',true),
('REFINE_RECOMMENDATION_DOCS_CNT','20','vector db',false),
('DOCUMENT_METASTORE_NAME','cssit_documentmetastore','vector db',false),
('EMBEDDING_MODEL','embeddinggemma-300m','Gen Ai',true),
('IMAGE_TO_TEXT_MODEL','gemma-3-27b-it','Gen Ai',true),
('TEXT_TO_TEXT_MODEL','llama-3-3-70b-instruct','Gen Ai',true),
('EMBED_LOCAL','False','refine recommendation',true),
('REF_REC_SIMILARITY_THRESHOLD','0.05','refine recommendation',true),
('AN_EVENT_TABLE','an_event','database objects',true),
('STATEMENTOFWORK_TABLE','tstatementofwork','database objects',true),
('DOCUMENT_TABLE','tdocument','database objects',true),
('RECOMMENDATION_TABLE','trecommendation','database objects',true),
('FEEDBACK_TABLE','tfeedback','database objects',true),
('EXTRACTION_TABLE','textraction','database objects',true),
('TOBEREDACTED_TABLE','ttoberedacted','database objects',true),
('DTPMMAPPING_TABLE','tdtpm_mapping','database objects',true),
('REDACTED_TABLE','tredacted','database objects',true),
('APICALL_LOGS_TABLE','tapi_call_logs','database objects',true),
('CHANGE_DOCUMENT_TABLE','tchange_document','database objects',true),
('CLASSIFICATIONOUT_VIEW','vwclassificationout','database objects',true),
('DOCUMENTS_VIEW','vwdocuments','database objects',true),
('GETRECOMMENDATIONS_VIEW','vwgetrecommendation','database objects',true),
('OFFERFAMILYDATA_VIEW','vwofferfamilydata','database objects',true),
('RECOMMENDATIONS_VIEW','vwrecommendations','database objects',true),
('STATEMENTOFWORK_VIEW','vwstatementofwork','database objects',true),
('DTPMMAPPING_VIEW','vwdtpmmapping','database objects',true),
('GENERATE_RECOMMENDATION_FUNCTION','fngeneraterecommendation','database objects',true),
('LLM_RAW_RESPONSE_TABLE','tllm_raw_response','database objects',true),
('REFINE_RECOMMENDATION_VIEW','vwGetRefineRecommendation','database objects',true),
('DISABLE_SENDING_MESSAGE','true','Kafka config',false),
('CHUNKING_SWITCH_REDACTION','true','gtl flow',false),
('CHUNKING_SWITCH_CLASSIFICATION','true','gtl flow',false),
('CHUNKING_SWITCH_RECOMMENDATION','true','consultant flow',false)
;
